### ISSUE TITLE
Reference ID convention - (උදා. GMS/PS/2020/012345) 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#131] opened 2020-04-29 10:10 UTC
Change reference ID conventio to Reference ID convention - (උදා. PS/DPA/2020/012345) - 

Includes: 
- GMS 
- Org such as Presidential Secretariat
- Year 
- Sequence number

**Comment by umayangag** [comment] 2020-04-30 11:15
Ref Id was designed to be generated at object construction. Since organization code needs to be taken in order to generate the refID. Had to move the refId generation to the service controller.

**Comment by MrClemRkz** [comment] 2020-04-30 13:26
it's all cool. just that we need to see if there's a possibility of having duplicates.

**Comment by MrClemRkz** [comment] 2020-05-01 05:13
tested and merged.

**Closed by MrClemRkz** 2020-05-01 05:13 UTC
Labels: Priority 1
